name: request_builder
description: A new Flutter package.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:

  equatable: ^2.0.5
  flash: ^3.1.0
  lottie: ^2.7.0
  intl: any
  auto_size_text: any
  overlay_support: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
  assets:
    - assets/json/
