name: request_builder
description: A new Flutter package.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  lottie: ^2.7.0
  equatable: ^2.0.5
  flash: ^3.1.0
  intl: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
  assets:
    - assets/json/
